namespace Corpa4Sem4.Database.Models
{
    public class ClientStatusOdb
    {
        public string ClientStatus = @"
-- public.""ClientStatus"" definition

-- Drop table

-- DROP TABLE public.""ClientStatus"";

CREATE TABLE public.""ClientStatus"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Value"" varchar(50) NOT NULL,
    CONSTRAINT ""PK_ClientStatus"" PRIMARY KEY (""Id"")
);";
    }
}