namespace Corpa4Sem4.Database.Models
{
    public class GenderOdb
    {
        public string Gender = @"
-- public.""Gender"" definition

-- Drop table

-- DROP TABLE public.""Gender"";

CREATE TABLE public.""Gender"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Value"" varchar(10) NOT NULL,
    CONSTRAINT ""PK_Gender"" PRIMARY KEY (""Id"")
);";
    }
}