namespace Corpa4Sem4.Database.Models
{
    public class LegalPersonOdb
    {
        public string LegalPerson = @"
-- public.""LegalPerson"" definition

-- Drop table

-- DROP TABLE public.""LegalPerson"";

CREATE TABLE public.""LegalPerson"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Address"" varchar(255),
    ""CeoId"" int4,
    ""BookkeeperFullName"" varchar(100),
    ""PhoneNumber"" varchar(15),
    ""OwnershipId"" int4,
    CONSTRAINT ""PK_LegalPerson"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_LegalPerson_Ceo"" FOREIGN KEY (""CeoId"") REFERENCES public.""NaturalPerson"" (""Id""),
    CONSTRAINT ""FK_LegalPerson_Ownership"" FOREIGN KEY (""OwnershipId"") REFERENCES public.""Ownership"" (""Id"")
);";
    }
}