namespace Corpa4Sem4.Database.Models
{
    public class LoanOdb
    {
        public string Loan = @"
-- public.""Loan"" definition

-- Drop table

-- DROP TABLE public.""Loan"";

CREATE TABLE public.""Loan"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""PaymentDate"" date NOT NULL,
    ""DebtAmount"" numeric(15,2) NOT NULL,
    ""Closed"" bool NOT NULL,
    ""AccountId"" int4 NOT NULL,
    CONSTRAINT ""PK_Loan"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_Loan_Account"" FOREIGN KEY (""AccountId"") REFERENCES public.""Account"" (""acc_id"")
);";
    }
}