namespace Corpa4Sem4.Database.Models
{
    public class NaturalPersonOdb
    {
        public string NaturalPerson = @"
-- public.""NaturalPerson"" definition

-- Drop table

-- DROP TABLE public.""NaturalPerson"";

CREATE TABLE public.""NaturalPerson"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Name"" varchar(50),
    ""Surname"" varchar(50),
    ""Patronymic"" varchar(50),
    ""Address"" text,
    ""PhoneNumber"" varchar(15),
    ""SexId"" int,
    ""StatusId"" int,
    ""InStaffId"" int,
    CONSTRAINT ""PK_NaturalPerson"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_NaturalPerson_Gender"" FOREIGN KEY (""SexId"") REFERENCES public.""Gender"" (""sex_id""),
    CONSTRAINT ""FK_NaturalPerson_ClientStatus"" FOREIGN KEY (""StatusId"") REFERENCES public.""ClientStatus"" (""status_id""),
    CONSTRAINT ""FK_NaturalPerson_StaffStatus"" FOREIGN KEY (""InStaffId"") REFERENCES public.""StaffStatus"" (""in_staff_id"")
);";
    }
}