namespace Corpa4Sem4.Database.Models
{
    public class OwnershipOdb
    {
        public string Ownership = @"
-- public.""Ownership"" definition

-- Drop table

-- DROP TABLE public.""Ownership"";

CREATE TABLE public.""Ownership"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Value"" varchar(100) NOT NULL,
    CONSTRAINT ""PK_Ownership"" PRIMARY KEY (""Id"")
);";
    }
}