namespace PraktASPApp.Database.Models
{
    public class StaffStatusOdb
    {
        public string StaffStatus = @"
-- public.""StaffStatus"" definition

-- Drop table

-- DROP TABLE public.""StaffStatus"";

CREATE TABLE public.""StaffStatus"" (
    ""Id"" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
    ""Value"" varchar(50) NOT NULL,
    CONSTRAINT ""PK_StaffStatus"" PRIMARY KEY (""Id"")
);";
    }
}